### ISSUE TITLE
$sort get lost on socket updates

### ISSUE THREAD

**Issue by barata0** [feathers-plus/feathers-vuex#103]
### Steps to reproduce
I created a service called entries with a date property. This property is used to sort the list.
My vue component fetch the entries when mounted and the client should automatically update the list through socket events.
Just created the feathers-client.js and the store/index.js according to the doc:
[https://github.com/feathers-plus/feathers-vuex](https://github.com/feathers-plus/feathers-vuex)

```
// feathers-client.js
import feathers from '@feathersjs/feathers'
import socketio from '@feathersjs/socketio-client'
import auth from '@feathersjs/authentication-client'
import io from 'socket.io-client'

const socket = io('http://localhost:3030', {transports: ['websocket']})

const feathersClient = feathers()
  .configure(socketio(socket))
  .configure(auth({ storage: window.localStorage }))

export default feathersClient
```

```
// store/index.js
import Vue from 'vue'
import Vuex from 'vuex'
import feathersVuex from 'feathers-vuex'
import feathersClient from '../feathers-client'

const { service, auth } = feathersVuex(feathersClient, { idField: '_id' })

Vue.use(Vuex)

export default new Vuex.Store({
  plugins: [
    service('entries'),
    auth()
  ]
})
```

At my-component.vue
...
```
  mounted: function () {
    this.fetchEntries({query: {$limit: 1000, $sort: {date: 1, _id: 1}}})
  },
  methods: {
    ...mapActions('entries', {fetchEntries: 'find'})
  },
  computed: {
    ...mapGetters('entries', {findEntries: 'find'}),
    filteredEntries: function () {
      return this.findEntries({query: {$limit: 1000, $sort: {date: 1, _id: 1}}})
    }
  }

```
...

### Expected behavior
After receiving a socket update for a service, the list should be sorted (the new item should not be added to the end of the list but according to the correct sort param)

### Actual behavior
The 1st time data is loaded, it is perfectly sorted, but when the client receives socket updates the sort is lost and the new items are added at the end of the list

### System configuration

  "dependencies": {
    "@ feathersjs/authentication-client": "^1.0.2",
    "@ feathersjs/feathers": "^3.1.3",
    "@ feathersjs/socketio-client": "^1.1.0",
    "feathers-vuex": "^1.1.4",
    "socket.io-client": "^2.0.4",
    "vue": "^2.5.2",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  },

**NodeJS version**: 8.9.4

**Operational System**: ubuntu 17-10 64 bits

**Browser Version**: Chrome 64.0.3282.119 and Firefox 59.0.1

**Comment by gpolitog** [comment]
I have similar issues and made several experiments.

**My TL;DR main finding is:**

the find GETTER fails to sort by more than one field.  Limitation or bug?

**My full findings so far are:**

The find ACTION fails to sort when you try to sort by a fastJoint-ed field.  But is not a feathers-vuex issue, because when using a REST client (postman), result is the same.  So it may be a (normal?) limitation, at least when using the feathers-neDB adapter.  
However, I successfully sorted by 3 fields that are "natural" (not fast-Joint-ed) fields, both with feathers-vuex's find action, and with postman (directly querying the server with no UI).

Nevertheless, once the data is in the store, it is just like local data, so there is no more distinction between natural and fastJoint-ed fields, since they all are just properties of objects in the store.

However, the find GETTER fails to sort by more than one field.

IMO, this is a concern because the UI (and the UX) is driven by the find getter, not by the find action.

I don't know if it is a limitation or a bug in feathers-vuex' find getter, but any hint on the better workaround will be greatly appreciated.   For my use case, I really need to sort by several fields.

feather-vuex is a geat tool anyway.

**Comment by marshallswain** [comment]
Dang.  This is probably an issue with the underlying `sift` package (https://www.npmjs.com/package/sift) which we're using to support more MongoDB query syntax.  Can you try downgrading one version below `v1.1.4` and see if there's still an issue?  (I imagine there will be even more issues, honestly, but I don't know)

**Comment by barata0** [comment]
Hi,

How (and where) should I downgrade it? (ps. I couldn´t find it on any package.json)?

I tried `npm i -s sift@1.1.4` on the vue project root but it didn´t change anything

Anyway, i figure it out that this only happens having multiple sort properties, **removing** _id **from $sort** works fine

```
filteredEntries: function () {
    return this.findEntries({query: {$limit: 1000, $sort: {date: 1}}}).data
}
```

**Comment by gpolitog** [comment]
@barata0 Did you close the issue because you found a solution?  If so, please share.

**Comment by marshallswain** [comment]
@barata0 I was referring to downgrading feathers-vuex.

**Comment by marshallswain** [comment]
I'm going to leave this open, unless you found a solution @barata0

**Comment by barata0** [comment]
Sorry,

I didn´t wanted to close.

I´ll try downgrading feathers-vuex and let u know

**Comment by marshallswain** [comment]
This is fixed in `feathers-vuex@1.6.2`

**Comment by HarisHashim** [comment]
I am experiencing same problem.

Initially I thought it is just sort. But it turns out the whole query param is ignored when there is socket update.

Bellow is my param

```
      let findNotificationParam = {
        query: {
          $sort: {uid: -1},
          $limit: 10,
          toId: this.userid
        }
      };
```

Basicly this is for receiving notification. There is two way that my notification list UI is updated. 

One is when the page is first loaded or refreshed. 

Two is when socket io update the notification list and will update the UI also.

The first work, the second did not work. Let say I have 2 user using the web app. Both user will receive notification when by right only user referred to by toId user should receive it.

When I do a refresh (i.e the first way), the notification list will become correct. I have no idea how to troubleshoot and solve this.  Probably will figureout a work around on the backend feathersjs side.

This is from my package.json

    "feathers-vuex": "^1.6.2",

**Comment by marshallswain** [comment]
@HarisHashim please try doing `npm i feathers-vuex@pre` and testing again. 

As a workaround, you can manually use a lodash `orderBy(collection, 'fieldName')` on the array returned from the getter.
