### ISSUE TITLE
Custom Service action not returning response

### ISSUE THREAD

**Issue by drewrawitz** [feathers-plus/feathers-vuex#182]
So I set up a custom service called `forgot-password` and inside my class, I have:

```
class Service {
  constructor (options) {
    this.options = options || {};
  }

  async create () {
    return {
      message: 'Thanks!'
    };
  }
}

module.exports = function (options) {
  return new Service(options);
};

module.exports.Service = Service;
```

I removed all of my custom logic and just made it super simple for this example, where i'm returning an object.

Now if I POST to `{{hostname}}/forgot-password` I get the correct response:
![postman 2018-11-16 10-03-18](https://user-images.githubusercontent.com/5014932/48635983-de580500-e986-11e8-915f-adf617596031.png)

But if I go to my Vue app and try to create a new forgot-password request with the following code:

```
  methods: {
    ...mapActions({
      forgotPassword: "forgot-password/create"
    }),
    async onSubmit() {
      await this.forgotPassword({
        email: this.credentials.email
      }).then(res => {
        console.log(res);
      });
    }
  }
```

I'm always getting `undefined` back.  This seems so simple, but I cannot seem to figure out what's going on. Is there anything I'm missing?

Thanks!

**Comment by J3m5** [comment]
I think it's because the service doesn't have a model, and feathers-vuex rely on them.
I have the same problem but with a database service, I use it to make a mongodb aggregate query so the result structure doesn't match with the mongoose model and Feahters-Vuex discard the result and don't store it.
It not mentio'ned anywhere in the docs and I don't know if it's possible to pass a custom model or to bypass it.

It's a bit annoying, @marshallswain, is there any way to circumvent this behavior?

**Comment by marshallswain** [comment]
Feathers-Vuex is optimized inside to map by id.  You have to specify an id or return an id in the response, or the record will be discarded.  

You can get around this by using the Feathers client directly.  It doesn’t make sense to use Feathers-Vuex for something that’s not going to be stored in Vuex.

**Comment by marshallswain** [comment]
I've added a note to each of the service actions in the documentation: https://feathers-plus.github.io/v1/feathers-vuex/service-module.html#Service-Actions
