### ISSUE TITLE
Mixins do not support $like when querying a server that does support it

### ISSUE THREAD

**Issue by jondmoon** [feathers-plus/feathers-vuex#217]
Feathers-knex includes an additional query mechanism for $like, which the feathers-vuex mixins do not understand and throw an error. I have it set up to always load the data from the server and not to use local storage, but it apparently still tries to filter on the client-side and that filtering is causing an error. The data coming from the server looks correct, returning a number of records, but there is a console error for "BadRequest: Invalid query parameter $like". Is it possible (through an additional option, perhaps) to have the mixins not try to filter the data on the client and bypass this process? I feel like that would be easier than trying to make it compatible with all of the custom options that the different adapters have while still allowing this to work.

### Steps to reproduce
Query against an feathers-knex service and include a $like in the query params. Querying the server directly via REST works and returns data, but gives an error in the console when trying to use a mixin through feathers-vuex.

### Expected behavior
If the service is set up to not use local data and the query returns data from the server, that data should be able to be retrieved without client-side parsing (or make the client-side parsing compatible with the additional query parameters supported by the different clients).

### Actual behavior
BadRequest: Invalid query parameter $like

**Comment by marshallswain** [comment]
There are a couple of solutions to this issue, but first a review of why this is an issue.

Under the hood, Feathers-Vuex uses the [sift module](https://www.npmjs.com/package/sift).  It's based on the MongoDB syntax, so it works great with MongoDB and Mongoose services without much effort.  Since `$like` is not a MongoDB operator, it's not currently supported by `sift`.

However, the error that you are seeing is not from `feathers-vuex` or the `sift` module.  it's a security feature baked into Feathers which prevents mal-intended params from going to the server.  It's customizable, as I've noted later in this comment.

The possibly simplest workaround for this is to use a separate set of params for the `find` action than what is used for the `find` getter.  Since you're using the `makeFindMixin` utility, you would accomplish this by having a `<serviceName>FetchParams` property.

```js
import { makeFindMixin } from 'feathers-vuex'

export default {
  name: 'my-component',
  mixins: [
    makeFindMixin({ service: 'todos' })
  ],
  computed: {
    // Sent to the find getter
    todosParams () {
      return { query: { /* maybe you can use $regex to accomplish something similar */ } }
    },
    // Sent to the find action (so also to the server)
    todosFetchParams () {
      return { query: { name: { $like: 'whatever' } } } // or however you use $like
    }
  }
}
```

Having a `todosFetchParams` property is a convention that's baked into the mixin which will cause it to send those params to the server.  The `todosParams` will only be used for the getter.  Notice my comment in the `todosParams` query.  You *might* be able to use the `$regex` operator, which is built in to the `sift` module: https://www.npmjs.com/package/sift#regex. I'm not sure if you'd be able to get the exact same results, though.

Another option would be for you to use the `paramsForServer` or `whitelist` arrays.  I'm not sure if they're in the docs, but they should be documented in the code.  These allow you to specify custom params that the Feathers client will allow to be sent to the server AND the `find` getter.  If you add `$like` to the list, you'll need to use the `sift` module's new feature which allows for adding new operators.  You can try following the `sift` docs to create a custom expression.  I don't know enough about it to know if you'll have any success because I haven't needed them, yet.

The third workaround is the one that I tend to use the most when I run into this circumstance.  That workaround is to use the `find` getter to get as much of the query as possible to match the params sent to the server.  Then I use a separate computed property in my component to tap into pure JS `.filter` and get the results I want that way.

```js
// extending the previous example (remember that the mixin already setup the `todos` array
  computed: {
    filteredTodos() {
      return this.todos.filter(i => {
        return i.includes('whatever') // or whatever condition works for your scenario
      }
    }
  }
```

**Comment by jondmoon** [comment]
Thanks, this is helpful. I was doing a variation of option 3 but I was still trying to do too much with the query and thus wasn't using the mixin. Now I can use the mixins, which I find very helpful and save a lot of time.

Thanks!
