### ISSUE TITLE
Not fetching data at reload

### ISSUE THREAD

**Issue by fbalazsy** [feathers-plus/feathers-vuex#220]
### Steps to reproduce

Hi, I am facing strange behaviour with this setup. 

Server: https://bitbucket.org/terminator68/feathers-test-issue/src/master/  
Client: https://bitbucket.org/terminator68/vue-test-issue/src/master/ 

When I put text in input form and press button, it will add it to database, as expected, and show database content through getter. As soon as i restart page, content gets lost. I am able to get all stored content through get request in Postman. Could somebody please told what I am doing wrong, that data could not fetch correctly when reloading page ? Thank you very much..

**Module versions** (especially the part that's not working):
Super fresh, could see in repos.
**NodeJS version**:
v10.15.3
**Operating System**:
Darwin

**Comment by barata0** [comment]
Hi,


You are not FETCHING the data at any time at all.

When you add a new record the socket event updates the VUEX store with the new ADDED record.

You should map the action find [see here](https://feathers-vuex.feathers-plus.com/service-module.html#find-params)

And call this method at the mounted event. [see here](https://vuejs.org/v2/guide/instance.html#Lifecycle-Diagram)

```
mounted () {
    this.fetchTests()
},

```
```
...mapActions('test', {
      createTest: 'create',
     fetchTests: 'find'
}),

```

Ps. Be careful because the default pagination limits to 10 records. If you want to fetch all the data you should increase it or iterate over the results.

**Comment by marshallswain** [comment]
@fbalazsy if you follow what @barata0 said, it should fix your issue.  Please reopen if you continue to experience a problem.
