### ISSUE TITLE
Send data to database with feathers-vuex

### ISSUE THREAD

**Issue by edatoprak** [feathers-plus/feathers-vuex#233]
I have a project with vue.js and feathers.js. I have creat datagrid with vuetify. I want to send the data inside the datagrid  to our mysql database with Feathersvuex.  On backend side i have used Feathers-sequelize for DB connection. How can i save the data in Vuex store and then send to the database?

**Comment by marshallswain** [comment]
I highly recommend using the [data modeling](https://feathers-vuex.feathers-plus.com/model-classes.html) system for this.  You would loop through each record and create a model instance out of it.  Make sure the data matches your expected columns, then just call `instance.save()`.  Here's an example using the latest pre-release.  

```
async saveDataMethod() {
  const todoCreates = this.dataInTable.map(r => new this.$FeathersVuex.myApi.Todo(r).save())

  const savedTasks = Promise.all(todoCreates) // <-- you want to try-catch this
  console.log(savedTasks) // <-- Each record should have an `id`
}
```

The only difference with the current version of `feathers-vuex` would be the structure of the `$FeathersVuex` object.  You'd find the model at `this.$FeathersVuex.Todo(data)` instead of under the `serverAlias` called `myApi`.

**Comment by marshallswain** [comment]
I'm going to close this.  If you require more clarity, feel free to reopen and comment.
