### ISSUE TITLE
Model required on makeServicePlugin

### ISSUE THREAD

**Issue by bartduisters** [feathers-plus/feathers-vuex#257]
### Steps to reproduce
Use "feathers-vuex": "^2.0.0-pre.75"
Follow https://github.com/feathers-plus/feathers-vuex/pull/216 to set up the project. (I moved files around from a working v3 feathers app to have an identical setup to this one).

When skipping the Model assignment in the makeServicePlugin, it gives a very unclear error.
![image](https://user-images.githubusercontent.com/43420049/64288104-887a3b00-cf61-11e9-8084-3136d8bc2f82.png)

It took me a while to figure out that a Model has to be defined. However, I find this odd, since on the backend this is a service without a model:
![image](https://user-images.githubusercontent.com/43420049/64288440-69c87400-cf62-11e9-9dc0-8653850c6adb.png)
The lines in comments are NOT there, I added them to show that they are NOT used.

My current workaround is to configure a Model anyway on the client:
![image](https://user-images.githubusercontent.com/43420049/64288518-9aa8a900-cf62-11e9-8dc7-ead0b6e291e0.png)

This makes the error go away. But it feels strange to define a model on the frontend, while not having one on the backend. Is this as intended?

**Comment by marshallswain** [comment]
Thanks for opening the issue, @bartduisters.  A Model class is required by design for `feathers-vuex@2.x`.  This needs to be made more clear in the documentation and appropriately communicated when not provided.  What you've done is the correct implementation.

The data modeling is the best feature of feathers-vuex.  I highly recommend getting used to it.  It saves way more boilerplate from 1.x.
