### ISSUE TITLE
setCurrent copy only works with object, not when passing id

### ISSUE THREAD

**Issue by plasticrake** [feathers-plus/feathers-vuex#48]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [x] Tell us what broke. The more detailed the better.
- [x] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

### Expected behavior
When calling mutation `setCurrent(id)` it should copy the current item into `copy` per the README

### Actual behavior
If `id` is passed the copy is set to the `id` instead of the object.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions**
feathers-vuex: 0.8.0

**NodeJS version**: v8.5.0

**Comment by marshallswain** [comment]
@plasticrake that's definitely unexpected, can you try setting a breakpoint at this point in the code and checking why it would be failing: https://github.com/feathers-plus/feathers-vuex/blob/master/src/service-module/mutations.js#L130 ?

My best guess is that you're maybe using MongoDB ObjectIds as the id, instead of the stringified versions of them, so it passes the `isObject` check.

**Comment by plasticrake** [comment]
I created a pull request (#49) based on my understanding of how setCurrent should work. I included a test that shows the issue I'm having.

**Comment by marshallswain** [comment]
I've merged #49.  Thank you!
