### ISSUE TITLE
How can I keep authenticated in all components

### ISSUE THREAD

**Issue by ricardopolo** [feathers-plus/feathers-vuex#82]
I need to use feathersVuex actions in lots of components. I dont want to put `this.$store.dispatch('auth/authenticate')` in every component to use the vuex store.

Where would you recommend that line of authentication?
I tried in the `mounted()` of `App.vue`, but it does not work

Thanks

**Comment by marshallswain** [comment]
This issue has to be handled in your application architecture.  Generally, to prevent having to authenticate in every component, you would set up your app with an "authenticate gateway" architecture, so that any component which makes queries which require auth would not instantiate until after the app is authenticated.
